Feature/kgfu02/create side navigation component
TritonSE/TSE-Moneta pull request #26
Opened 2022-01-13 00:02 UTC by kgfu02

### Administrative Info
[GitHub Issue #]
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- added a side navigation component that has positionally styled buttons to be used for navigation
- added css styling to App.css
- import side navigation to App.js

### Testing
How did you confirm your changes worked? 
- checked npm start

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| Side navigation bar |
| --- |
| <img width="1440" alt="Screen Shot 2022-01-12 at 3 59 29 PM" src="https://user-images.githubusercontent.com/51866248/149241926-99af9880-3fc3-4f8d-8c48-da59bb64971c.png">|

2022-01-14 01:52 UTC, eliasfang approved these changes
Not too sure where we'll be placing our page components since I noticed you put yours in a components folder but it looks great overall!🤘🏼

2022-01-14 02:54 UTC, wllmwu requested changes
Some suggestions about your CSS, otherwise looks good.

2022-01-14 02:54 UTC, wllmwu commented on frontend/src/components/SideNavigation.js
> +      </button>
I'd recommend against inline styles - the best thing to do here would probably be to create a CSS class for each type of button and use those here.

2022-01-14 02:54 UTC, wllmwu commented on frontend/src/components/SideNavigation.js
> +    <div className="SideNavigation">
I believe the convention for CSS class names is kebab-case, so this should have `className="side-navigation"`.

2022-01-14 02:54 UTC, wllmwu commented on frontend/src/App.css
> -
I'd suggest restoring this file to its original state and placing your CSS in a new file next to your `SideNavigation.js`, probably called `SideNavigation.css`. If we put all our CSS in the same file, it would be a lot harder to find the relevant part when we want to change it.

2022-01-14 03:48 UTC, eliasfang commented on frontend/src/components/SideNavigation.js
> +    <div className="SideNavigation">
I didn't know it was called kebab-case! That's so interesting

2022-01-14 20:16 UTC, wllmwu requested changes
Looks pretty good to me! Just need to fix the formatting in `SideNavigation.css` and you'll be good to go. Also I think you accidentally added `backend/tableData.model.js` to this branch, you can use `git rm` to untrack it and remember to create a new branch for your next task.

2022-01-14 20:16 UTC, wllmwu commented on frontend/src/components/SideNavigation.css
> +    height: 100%;
CSS should also be indented with 2 spaces according to TSE rules, I think. You can install the [Prettier VSCode extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) and have it automatically format your files, which is nice and will help us avoid formatting conflicts in the future

2022-01-14 20:16 UTC, wllmwu commented on frontend/src/components/SideNavigation.css
> +}
Note for future: the database, admin, and settings buttons are all basically the same, just with different labels and icons. I think that suggests that these buttons could be refactored into a separate component with a single set of styles. But that can be done when the styling is updated.

2022-01-15 00:36 UTC, kgfu02 commented on frontend/src/components/SideNavigation.css
> +    height: 100%;
Oh ok, thanks for the tip!

2022-01-15 07:11 UTC, wllmwu approved these changes
Nice work! 👌

2022-01-15 22:00 UTC, navidboloorian approved these changes
Great stuff Kevin! The relative positioning makes sure that it looks good even on resizing the screen. Shoutout to @wllmwu and @eliasfang for the great feedback as well. Go ahead and merge!

2022-01-15 22:00 UTC, navidboloorian commented
> Not too sure where we'll be placing our page components since I noticed you put yours in a components folder but it looks great overall!🤘🏼

I'll be adding a pages folder and refactoring some stuff once the current PRs are approved.

2022-01-15 22:03 UTC, merged