Feature/kgfu02/new group module
TritonSE/TSE-Moneta pull request #43
Opened 2022-02-06 20:32 UTC by kgfu02

### Administrative Info
[GitHub Issue #]
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- created new group module

### Testing
How did you confirm your changes worked? 
- tested by viewing module in browser using npm start

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| Create group module |
| --- |
| <img width="720" alt="Screen Shot 2022-02-06 at 12 31 21 PM" src="https://user-images.githubusercontent.com/51866248/152700211-ab2dd4db-5207-4e1a-9574-3397dede0d88.png"> |

2022-02-09 20:32 UTC, navidboloorian requested changes
Great stuff as usual Kevin! It's not necessary to add the createGroup component to router. Instead, just have it on the dashboard page because that is where it will be used.

2022-02-11 07:47 UTC, kgfu02 commented
I'm not sure why but moving the module to the dashboard messed up the styling slightly. @navidboloorian Do you know why this is happening?
<img width="1440" alt="Screen Shot 2022-02-10 at 11 43 50 PM" src="https://user-images.githubusercontent.com/51866248/153554277-7b6e7810-ad73-40cd-99b1-28058ecdc383.png">

2022-02-12 03:31 UTC, navidboloorian commented
> I'm not sure why but moving the module to the dashboard messed up the styling slightly. @navidboloorian Do you know why this is happening? <img alt="Screen Shot 2022-02-10 at 11 43 50 PM" width="1440" src="https://user-images.githubusercontent.com/51866248/153554277-7b6e7810-ad73-40cd-99b1-28058ecdc383.png">

I think there might be some menu specific styling going on. Check the styles sources with inspect element. There might also be some wild card styling (*{whatever}) that applies to every element. If that's the case will likely need to be tweaked.

2022-02-13 02:51 UTC, navidboloorian approved these changes
LGTM

2022-02-14 20:57 UTC, wllmwu requested changes
Looks good to me, assuming the functionality of this component + integration into dashboard will be implemented in the future. Just remember to remove the import from `index.js` if it's not used there. 👍

2022-02-14 20:57 UTC, wllmwu commented on frontend/src/components/CreateGroup.js
> +      <div className="modal-content">
I see there's no state or anything in this component yet. Assuming that's supposed to be implemented in a future task

2022-02-14 20:57 UTC, wllmwu commented on frontend/src/index.js
> +import CreateGroup from "./components/CreateGroup";
Remove import if not used

2022-02-15 05:30 UTC, kgfu02 commented on frontend/src/components/CreateGroup.js
> +      <div className="modal-content">
yep, just did the styling for now

2022-02-15 19:00 UTC, wllmwu approved these changes
Looks LGTM to me!

2022-02-15 21:59 UTC, merged