feature/pratyush1718/companyRoutes
TritonSE/TSE-Moneta pull request #47
Opened 2022-02-12 00:28 UTC by pratyush1718

### Administrative Info
[GitHub Issue #]
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Added company routes. Also fixed arrow function bug in Users schema

### Testing
How did you confirm your changes worked? 
- Ran all routes through postman

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.
![DELETE_Companies](https://user-images.githubusercontent.com/54123007/153687975-38e1029b-4e23-49f0-84d4-5a713302c7eb.png)
![GETall_Companies](https://user-images.githubusercontent.com/54123007/153688015-5639974d-5721-44c6-b8cf-a103917bf072.png)
![GET_Companies](https://user-images.githubusercontent.com/54123007/153688023-a5e73759-a7fe-4cf1-a459-5d62c7b93553.png)
![POST_Companies](https://user-images.githubusercontent.com/54123007/153688031-0ca055a6-6e1f-41a2-b9cd-5efdc5735705.png)
![PUT_Companies](https://user-images.githubusercontent.com/54123007/153688037-5e95d483-1513-4f72-afd6-ac106b171fec.png)

2022-02-12 14:58 UTC, navidboloorian approved these changes
LGTM!

2022-02-14 21:11 UTC, wllmwu requested changes
I noticed our routes don't seem to be RESTful. @navidboloorian your call on whether we should refactor them or not, since they've been this way for a while. If not then I'll approve 👍

2022-02-14 21:11 UTC, wllmwu commented on backend/models/Users.js
>    bcrypt.compare(enteredPassword, this.password, (err, matchBool) => {
Using `function () {}` syntax followed by arrow function `() => {}` syntax. Not really an issue but try to be consistent in the future

2022-02-14 21:11 UTC, wllmwu commented on backend/routes/companiesRoutes.js
> + * GET (/getAllCompanies)
These routes could be made more RESTful. For example,
```
POST /companies
DELETE /companies/:id
PUT /companies/:id
GET /companies/:id
GET /companies
```
The same goes for other routes, like the ones for users. In a RESTful API, each route's "action" is determined by the HTTP verb (GET = get, POST = create, etc.), so you don't need to repeat that in the route's path. And the routes are kind of named in terms of the resource, e.g. these routes deal with companies so they all have `/companies`.

This is just a housekeeping issue, doesn't affect the functionality, but I'm sure Justin would call it out during code quality checks.

2022-02-14 23:33 UTC, navidboloorian commented on backend/models/Users.js
>    bcrypt.compare(enteredPassword, this.password, (err, matchBool) => {
There've been some issues with this context with arrow function syntax. Good call to use function syntax as far as these backend issues are concerned.

2022-02-14 23:35 UTC, navidboloorian commented on backend/routes/companiesRoutes.js
> + * GET (/getAllCompanies)
I actually wasn't aware of this standard. @pratyush1718 please implement these changes in your route files. Going forward I'll be cognizant of this.

2022-02-15 19:03 UTC, wllmwu approved these changes
Great work! Hopefully this will please our overlord Justin.

2022-02-16 20:57 UTC, merged