Feature/ainesh01/organization schema
TritonSE/TSE-Moneta pull request #52
Opened 2022-02-22 00:27 UTC by navidboloorian

### Administrative Info
[GitHub Issue #] closing issue 21
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
Added Organizations Schema

### Testing
How did you confirm your changes worked? 
Ran testing code

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

![image](https://user-images.githubusercontent.com/20953846/153998493-0d23f853-0e14-4084-910a-e64c4562b8ca.png)

2022-02-22 19:41 UTC, eliasfang requested changes
Nice job overall! Just a small change. Also for future PR's I'd recommend adding a bit more description with the changes you made and how you tested it so that we can try reproducing what you got.

2022-02-22 19:41 UTC, eliasfang commented on backend/models/Users.js
> +UserSchema.methods.verifyPassword = function (enteredPassword) {
Missing a function header I believe

2022-02-22 22:56 UTC, pratyush1718 approved these changes
LGTM

2022-02-22 22:56 UTC, pratyush1718 commented on backend/models/Organizations.js
>    bcrypt.compare(enteredPassword, this.password, (err, matchBool) => {
Can we change this to a regular function instead of arrow? Just for consistency

2022-02-23 22:04 UTC, eliasfang approved these changes
Don't forget to do lint checks and fix any conflicts with main and then you should be good to go!

2022-02-23 22:18 UTC, merged