Feature/alexzhang1618/search
TritonSE/TSE-Moneta pull request #60
Opened 2022-03-02 23:20 UTC by alexzhang1618

### Administrative Info
[GitHub Issue #]
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Added a post route "/search" that returns a filtered table based on group and search params to TableDataRoutes.js
-  Updated props for Table.js to use data passed in by dashboard and updated table row keys to be based on id
- Added a search bar in the frontend that filters the table based on the search query

### Testing
How did you confirm your changes worked? 
- Ran the React app and looked at the result
- Tested the /search route using Postman

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| Table before search |
| --- |
| <img width="1440" alt="Screen Shot 2022-03-02 at 3 18 45 PM" src="https://user-images.githubusercontent.com/27360825/156466037-5cb973dc-6b3f-4421-beed-601ce8588576.png"> |

| Table after search |
| --- |
| <img width="1440" alt="Screen Shot 2022-03-02 at 3 19 47 PM" src="https://user-images.githubusercontent.com/27360825/156466144-37a67860-385a-45c7-a70f-e46654bbf52f.png"> |

2022-03-03 05:36 UTC, ainesh01 commented
@navidboloorian did anyone modify the linter to stop forcing arrow functions? Seems like same thing happened here, which will break the organizations and users schema

2022-03-03 19:51 UTC, navidboloorian commented
> @navidboloorian did anyone modify the linter to stop forcing arrow functions? Seems like same thing happened here, which will break the organizations and users schema

Yeah I have

2022-03-03 19:55 UTC, navidboloorian requested changes
The search functionality is amazing Alex, great work! In the model files, change the arrow functions back to nameless functions. I've updated the linter in the master branch to not ask for the change. We've been using nameless functions because "this" context is undefined when we use arrow functions.

2022-03-04 00:36 UTC, navidboloorian approved these changes
Looks amazing! Go ahead and rebase. If the model files give you conflicts on rebase, accept the changes from the master. I sorted out the linting there already.

2022-03-04 03:52 UTC, wllmwu approved these changes
Looks LGTM to me! Just some notes on conventions but I'm approving this anyway. I feel like half the time I spend writing JavaScript is me trying to look up the difference between this and that syntax or function.

2022-03-04 03:52 UTC, wllmwu commented on frontend/src/components/Table.js
> +function Table({ Data }) {
We seem to have a lot of things with the first letter capitalized, including in the schema. Not sure why that happened tbh this isn't AWS. Anyway convention for prop names, like any parameters or local variables, is to start with lowercase (except for a very particular case when React requires it to start with uppercase), so this would ideally be `data` instead of `Data`. Not a big deal though

2022-03-04 03:52 UTC, wllmwu commented on frontend/src/pages/Dashboard.js
> +    });
It's a little weird to combine `async/await` and `.then()`. If you wanted to use only one or the other approach you could do it like this:
```javascript
// with await
const response = await fetch("...", requestOptions);
const json = await response.json();
setTableData(json);
// might need a try-catch statement in case fetch() or json() fail
```
or
```javascript
// with promise chaining, I think
fetch("...", requestOptions)
  .then((response) => response.json())
  .then((json) => setTableData(json))
  .catch((error) => console.error(error));
```
I personally like `async/await` more because promise chains can be tough to follow. Currently though, we don't actually need the `await` in front of the `fetch()` because nothing happens afterwards in this effect function.

2022-03-04 19:45 UTC, merged